import {
  Box3,
  type BufferGeometry,
  Color,
  DoubleSide,
  Group,
  InstancedMesh,
  Matrix4,
  Mesh,
  MeshStandardMaterial,
  type PerspectiveCamera,
  Quaternion,
  type Texture,
  Vector3,
} from 'three';
import { RockPack, type RockPiece } from './RockPack';
import { KINGDOM, type KingdomTerrain, avenueMask } from './KingdomTerrain';
import {
  makeArch,
  makeBuilding,
  makeColumn,
  makeDrum,
  makeRubble,
  makeSlab,
  makeStairs,
  makeTower,
  makeWall,
  mulberry32,
} from './Masonry';
import type { AssetLoaderLike, CylinderCollider } from './types';

import columnUrl from '../../assets/fallen kingdom/column_compressed.glb?url';
import castleUrl from '../../assets/fallen kingdom/column_._column_with_arch._stone_column_compressed.glb?url';
import gemsLowUrl from '../../assets/fallen kingdom/gemstone_crystals_asset_pack_verylowpoly.glb?url';
import gemsMedUrl from '../../assets/fallen kingdom/stylized_crystal_gem_pack_mediumpoly.glb?url';
import bigCrystalUrl from '../../assets/fallen kingdom/stylized_crystal.glb?url';

// Vegetation. Cheap species carry the volume; the expensive ones appear in
// single figures as accents, and the luminescent plant — 26 k triangles each —
// appears a dozen times at enormous scale as the city's own lamps.
import algae1Url from '../../assets/drowned garden/algae_verylowpoly_1.glb?url';
import algae2Url from '../../assets/drowned garden/algae_verylowpoly_2.glb?url';
import seaweedUrl from '../../assets/drowned garden/seaweed_verylowpoly.glb?url';
import seaweed2Url from '../../assets/drowned garden/seaweed_2.glb?url';
import lowPolyPlantUrl from '../../assets/low-poly_plant.glb?url';
import lowPolyShrubUrl from '../../assets/low_poly_shrub.glb?url';
import coral2Url from '../../assets/coral_2.glb?url';
import marinePlantUrl from '../../assets/lowpoly_marine_plant.glb?url';
import lowpolyCoralUrl from '../../assets/lowpoly_coral.glb?url';
import coralPieceUrl from '../../assets/coral_piece.glb?url';
import luminescentUrl from '../../assets/luminescent_plants.glb?url';

/**
 * The Fallen Kingdom's content: a city, built as a city.
 *
 * The organising idea is that everything here is placed by a PLAN, never by a
 * scatter. A kingdom reads as a kingdom because of arrangement — an axis, a
 * hierarchy, an enclosure, districts — and no amount of good props survives
 * being sprinkled at random. So this file lays out, in order:
 *
 *   the CITADEL   a peristyle great hall on the acropolis plateau, its columns
 *                 standing, snapped, or fallen; a throne of raw crystal erupting
 *                 through the dais, directly under the breach's light;
 *   the STAIR     three flights climbing the acropolis flank, so the citadel is
 *                 approached rather than merely reached;
 *   the AVENUE    a processional colonnade running dead straight from the great
 *                 gate up to that stair — the single strongest signal in the
 *                 zone that people made this place;
 *   the GATE      twin towers and a half-fallen arch, where the avenue meets the
 *                 curtain wall;
 *   the WALL      a ring of crenellated curtain and towers, broken open where
 *                 the geode swallowed it;
 *   the TOWN      ranks of roofless building shells on the terraces, aligned to
 *                 tangential streets and radial ones, thinning as they climb;
 *   the GEODE     the collapse basin that ate the east quarter, where the
 *                 crystal that killed the city is laid bare.
 *
 * Everything structural is generated by {@link Masonry} rather than imported, so
 * ruin can be authored per piece. The .glb packs supply the hero pieces only —
 * the hall's columns, the great arches, and all the crystal — and every one of
 * their materials is replaced with this file's single shared stone, so the
 * modelled and the generated stone are literally the same rock.
 */

const UP = new Vector3(0, 1, 0);

/** Yaw that turns a piece built along +X so it runs TANGENTIALLY at angle `a`. */
function tangentYaw(a: number): number {
  return -(a + Math.PI / 2);
}

interface Placement {
  m: Matrix4;
  c: Color;
}

/** A spot where crystal or weed can take hold: a ledge, a wall top, a crack. */
interface Perch {
  x: number;
  y: number;
  z: number;
  /** Roughly which way the surface faces — bursts fan around this. */
  n: Vector3;
  /** Scale hint: how big a growth this spot can carry. */
  size: number;
}

export class KingdomDressing {
  readonly colliders: CylinderCollider[] = [];
  tris = 0;
  drawCalls = 0;

  private readonly disposables: { dispose(): void }[] = [];
  private packs: RockPack[] = [];
  private stone!: MeshStandardMaterial;
  private crystalMat!: MeshStandardMaterial;

  /** Accumulated instance placements, keyed by geometry + bucket. */
  private readonly queue = new Map<
    string,
    { geo: BufferGeometry; mat: MeshStandardMaterial; tris: number; items: Placement[] }
  >();

  /** Places crystal and weed can grow, gathered as the city is built. */
  private readonly perches: Perch[] = [];

  /** Everything down in the geode, so it can be culled when you are not. */
  private readonly geodeGroup = new Group();

  constructor(
    private readonly group: Group,
    private readonly terrain: KingdomTerrain,
    private readonly masonryTexture: Texture | null,
  ) {
    this.geodeGroup.name = 'kingdom-geode';
    this.group.add(this.geodeGroup);
  }

  async build(loader: AssetLoaderLike): Promise<void> {
    this.stone = this.makeStoneMaterial();
    this.crystalMat = this.makeCrystalMaterial();

    const [castle, column, gemsLow, gemsMed, bigCrystal] = await Promise.all([
      RockPack.load(loader, castleUrl),
      RockPack.load(loader, columnUrl),
      RockPack.load(loader, gemsLowUrl),
      RockPack.load(loader, gemsMedUrl),
      RockPack.load(loader, bigCrystalUrl),
    ]);
    this.packs.push(castle, column, gemsLow, gemsMed, bigCrystal);

    // The city is ONE stone. Every imported piece adopts the shared masonry
    // material, which unifies the modelled and generated architecture and drops
    // the castle pack's fourteen materials to a single draw state.
    for (const pack of [castle, column]) {
      for (const piece of pack.pieces) piece.material = this.stone;
    }

    this.buildCitadel(castle, column);
    this.buildGrandStair();
    this.buildAvenue(castle);
    this.buildGate(castle);
    this.buildCurtainWall();
    this.buildLowerTown();
    this.buildGeode(castle, bigCrystal);
    this.buildOutskirts();

    this.buildCrystal(gemsLow, gemsMed, bigCrystal);
    this.flush();
    await this.buildVegetation(loader);
  }

  // ---- materials ------------------------------------------------------------

  /**
   * The city's stone. White base so per-instance colour multiplies correctly,
   * plus a low emissive floor — this zone's only real light comes down one shaft
   * in the middle, and without a little self-illumination the outer town renders
   * at single-digit luminance and may as well not be there.
   */
  private makeStoneMaterial(): MeshStandardMaterial {
    const mat = new MeshStandardMaterial({
      color: 0xffffff,
      roughness: 0.94,
      metalness: 0,
      map: this.masonryTexture ?? undefined,
      emissive: new Color(0x11191f),
      emissiveIntensity: 1,
    });
    this.disposables.push(mat);
    return mat;
  }

  /**
   * The crystal. One material for every shard in the zone, but the emissive term
   * is patched to multiply by the per-instance colour.
   *
   * That patch is worth explaining: `emissive` is a uniform, so out of the box
   * every instance of an emissive material glows the identical colour — and a
   * geode where every crystal is the same blue looks like tinted glass, not like
   * a mineral bed. The alternative is one material per colour, which multiplies
   * draw calls. Three.js already provides `vColor` as a varying whenever
   * instance colours are in use, so redirecting the emissive through it buys
   * per-instance glow colour for free, and the whole crystal population still
   * renders in one draw state per shape.
   */
  private makeCrystalMaterial(): MeshStandardMaterial {
    // The body is DARK on purpose, and this is the counter-intuitive part.
    //
    // The renderer runs ACES filmic tone mapping at 1.18 exposure. ACES
    // desaturates as luminance climbs, so a white-based crystal lit by a 2.9
    // hemisphere plus a 5.4 key and then given a white emissive lands somewhere
    // around 5.0 radiance — and everything above ~1.5 is mapped to white
    // regardless of its hue. That is why the first pass rendered a geode full of
    // what looked like white paper sculpture no matter what colour was fed to
    // it. Keeping the diffuse dark holds total radiance inside the range where
    // ACES still preserves chroma, so the glow keeps its colour.
    const mat = new MeshStandardMaterial({
      // Near-black body: the crystal is SELF-LIT, not lit. Any real diffuse
      // response stacks on top of the emissive and pushes total radiance into
      // the range where ACES desaturates — and the throne sits directly under a
      // 5.4-intensity key, so it was the worst offender of the lot and came out
      // as pale grey-blue no matter how saturated its tint was.
      color: 0x080e14,
      roughness: 0.24,
      metalness: 0,
      emissive: new Color(0xffffff),
      emissiveIntensity: 1.35,
      flatShading: true,
    });
    mat.onBeforeCompile = (shader) => {
      // The guard MUST be USE_COLOR, not USE_INSTANCING_COLOR.
      //
      // three splits the two across stages: the vertex shader is compiled with
      // `USE_INSTANCING_COLOR` (that is where `instanceColor` is folded into
      // `vColor`), but the fragment shader for the same program is compiled with
      // `USE_COLOR` instead, and that is the define `color_pars_fragment` keys
      // its `varying vec4 vColor` declaration off. Guarding this on
      // USE_INSTANCING_COLOR therefore compiles perfectly cleanly, emits no
      // warning, and silently does nothing — every crystal in the zone glows
      // flat white and looks exactly like a material authoring mistake.
      shader.fragmentShader = shader.fragmentShader.replace(
        'vec3 totalEmissiveRadiance = emissive;',
        'vec3 totalEmissiveRadiance = emissive;\n' +
          '#if defined( USE_COLOR ) || defined( USE_COLOR_ALPHA )\n' +
          '  totalEmissiveRadiance *= vColor.rgb;\n' +
          '#endif',
      );
      // Recorded so a live check can tell "this colour is wrong" apart from
      // "the patch stopped matching after a three.js upgrade".
      mat.userData.emissivePatch = shader.fragmentShader.includes(
        'totalEmissiveRadiance *= vColor.rgb',
      );
    };
    this.disposables.push(mat);
    return mat;
  }

  // ---- the instance accumulator --------------------------------------------

  /**
   * Queue one placement. `bucket` splits a population into separately-culled
   * meshes — a ring of buildings sharing one InstancedMesh has a bounding sphere
   * covering the whole map and therefore never culls, so anything spread across
   * the city is bucketed by quadrant.
   */
  private add(
    key: string,
    geo: BufferGeometry,
    mat: MeshStandardMaterial,
    tris: number,
    m: Matrix4,
    c: Color,
    bucket = '',
  ): void {
    const k = bucket ? `${key}#${bucket}` : key;
    let q = this.queue.get(k);
    if (!q) {
      q = { geo, mat, tris, items: [] };
      this.queue.set(k, q);
    }
    q.items.push({ m: m.clone(), c: c.clone() });
  }

  /** Which quadrant a point is in — the bucket key for wide-spread populations. */
  private quad(x: number, z: number): string {
    return `${x < 0 ? 'w' : 'e'}${z < 0 ? 'n' : 's'}`;
  }

  private flush(): void {
    for (const [key, q] of this.queue) {
      if (q.items.length === 0) continue;
      const im = new InstancedMesh(q.geo, q.mat, q.items.length);
      im.name = `kingdom-${key}`;
      for (let i = 0; i < q.items.length; i++) {
        im.setMatrixAt(i, q.items[i].m);
        im.setColorAt(i, q.items[i].c);
      }
      im.instanceMatrix.needsUpdate = true;
      if (im.instanceColor) im.instanceColor.needsUpdate = true;
      // The geode's contents hang off their own group so they cull as a unit.
      (key.startsWith('geode') ? this.geodeGroup : this.group).add(im);
      this.drawCalls++;
      this.tris += q.tris * q.items.length;
    }
    this.queue.clear();
  }

  // ---- placement helpers ----------------------------------------------------

  /** Ancient wet stone, occasionally stained by the mineral coming up through it. */
  private tintStone(c: Color, rand: () => number): Color {
    const v = 0.46 + rand() * rand() * 0.5;
    c.setRGB(v, v * 1.01, v * 1.06);
    if (rand() < 0.2) c.lerp(STONE_STAIN, 0.15 + rand() * 0.35);
    return c;
  }

  /** Compose and queue a piece sitting on the ground at (x, z). */
  private put(
    key: string,
    geo: BufferGeometry,
    tris: number,
    x: number,
    z: number,
    rand: () => number,
    opts: {
      yaw?: number;
      scale?: number | Vector3;
      y?: number;
      sink?: number;
      tilt?: number;
      tiltAxis?: Vector3;
      bucket?: string;
      mat?: MeshStandardMaterial;
      color?: Color;
    } = {},
  ): void {
    const m = new Matrix4();
    const q = new Quaternion().setFromAxisAngle(UP, opts.yaw ?? rand() * Math.PI * 2);
    if (opts.tilt) {
      const lean = new Quaternion().setFromAxisAngle(
        opts.tiltAxis ?? new Vector3(1, 0, 0),
        opts.tilt,
      );
      q.multiply(lean);
    }
    const s =
      opts.scale instanceof Vector3
        ? opts.scale
        : new Vector3(opts.scale ?? 1, opts.scale ?? 1, opts.scale ?? 1);
    const y = (opts.y ?? this.terrain.heightAt(x, z)) - (opts.sink ?? 0);
    m.compose(new Vector3(x, y, z), q, s);
    const mat = opts.mat ?? this.stone;
    this.add(key, geo, mat, tris, m, opts.color ?? this.tintStone(SCRATCH_COLOR, rand), opts.bucket);
  }

  private triCount(geo: BufferGeometry): number {
    const idx = geo.index;
    return Math.round((idx ? idx.count : (geo.attributes.position as { count: number }).count) / 3);
  }

  /** Register a generated geometry for disposal and return its triangle count. */
  private own(geo: BufferGeometry): number {
    this.disposables.push(geo);
    return this.triCount(geo);
  }

  private perch(x: number, y: number, z: number, size: number, n?: Vector3): void {
    this.perches.push({ x, y, z, size, n: n ? n.clone() : UP.clone() });
  }

  // ---- the citadel ----------------------------------------------------------

  /**
   * The great hall: a peristyle on the acropolis plateau, with the throne at its
   * centre directly under the breach.
   *
   * Columns are placed on a real colonnade rhythm and then assigned a fate —
   * standing, snapped, or fallen — by position rather than at random, so the
   * collapse has a direction to it: the hall failed from its east end inward,
   * which is the side the geode is on. That single correlation is what turns a
   * mix of broken columns into a story about what happened here.
   */
  private buildCitadel(castle: RockPack, column: RockPack): void {
    const rand = mulberry32(4210);
    const HALF_X = 68;
    const HALF_Z = 50;
    const STEP = 22.5;
    const shaft = column.pieces[0];
    if (!shaft) return;

    // The plateau is flat, so one height serves the whole hall and the
    // colonnade's bases all line up the way a real stylobate does.
    const baseY = this.terrain.heightAt(0, 0);

    // The stylobate: a raised platform the whole hall stands on.
    const platGeo = makeWall(4400, {
      length: HALF_X * 2 + 26,
      height: 5.5,
      thickness: HALF_Z * 2 + 26,
      ruin: 0.12,
      courseHeight: 2.75,
    });
    const platTris = this.own(platGeo);
    this.put('citadel-stylobate', platGeo, platTris, 0, 0, rand, { yaw: 0, y: baseY - 4 });

    // --- the colonnade -------------------------------------------------------
    const spots: { x: number; z: number }[] = [];
    for (let x = -HALF_X; x <= HALF_X + 0.1; x += STEP) {
      spots.push({ x, z: -HALF_Z });
      spots.push({ x, z: HALF_Z });
    }
    for (let z = -HALF_Z + STEP; z < HALF_Z - 0.1; z += STEP) {
      spots.push({ x: -HALF_X, z });
      spots.push({ x: HALF_X, z });
    }

    // The shaft model is 0.6 wide x 2.0 tall, so one instance at width W is
    // 3.33 W tall; two stacked make a column of proper classical proportion —
    // here 8.6 m across and 57 m tall, which is the height that stops the hall
    // reading as a garden folly on top of a very large hill.
    const COL_W = 8.6;
    const segH = shaft.unitHeight * COL_W;
    const standing: { x: number; z: number; top: number }[] = [];

    for (const s of spots) {
      // Failure runs from the east (+X) end inward.
      const decay = (s.x + HALF_X) / (HALF_X * 2);
      const roll = rand();
      const fate = roll < 0.14 + decay * 0.5 ? (roll < 0.07 + decay * 0.24 ? 'fallen' : 'snapped') : 'standing';
      const y = baseY + 1.5;

      if (fate === 'standing') {
        for (let i = 0; i < 2; i++) {
          this.put('citadel-column', shaft.geometry, shaft.tris, s.x, s.z, rand, {
            scale: COL_W,
            y: y + i * segH * 0.985,
            yaw: rand() * Math.PI * 2,
          });
        }
        // A capital block, so the colonnade has something to carry the beams.
        const cap = castle.get('Object_66') ?? castle.get('Object_64');
        if (cap) {
          this.put('citadel-capital', cap.geometry, cap.tris, s.x, s.z, rand, {
            scale: COL_W * 1.15,
            y: y + segH * 1.97,
          });
        }
        const top = y + segH * 2;
        standing.push({ x: s.x, z: s.z, top });
        this.colliders.push({ x: s.x, z: s.z, r: COL_W * 0.46, top });
        this.perch(s.x, top, s.z, 9);
      } else if (fate === 'snapped') {
        this.put('citadel-column', shaft.geometry, shaft.tris, s.x, s.z, rand, {
          scale: COL_W,
          y,
          yaw: rand() * Math.PI * 2,
        });
        this.colliders.push({ x: s.x, z: s.z, r: COL_W * 0.46, top: y + segH });
        this.perch(s.x, y + segH, s.z, 11);
        // The rest of it lying where it came down.
        this.scatterDrums(s.x, s.z, COL_W * 0.5, 3, rand, y);
      } else {
        // Fallen outright: a line of drums pointing away from the hall.
        this.scatterDrums(s.x, s.z, COL_W * 0.5, 6, rand, y);
      }
    }

    // --- the architrave ------------------------------------------------------
    // Beams laid across pairs of columns that both survived and are adjacent.
    const beam = castle.get('Object_100') ?? castle.get('Object_98');
    if (beam) {
      // Object_100's long axis is X; Object_98's is Z. Pick the yaw accordingly.
      const longAlongX = beam.unitWidth >= beam.unitDepth;
      for (let i = 0; i < standing.length; i++) {
        for (let j = i + 1; j < standing.length; j++) {
          const a = standing[i];
          const b = standing[j];
          const d = Math.hypot(b.x - a.x, b.z - a.z);
          if (d > STEP * 1.15) continue;
          if (rand() < 0.42) continue; // most of the entablature is down
          const dir = Math.atan2(b.z - a.z, b.x - a.x);
          this.put('citadel-beam', beam.geometry, beam.tris, (a.x + b.x) / 2, (a.z + b.z) / 2, rand, {
            scale: d * 1.06,
            y: Math.min(a.top, b.top) + 1,
            yaw: longAlongX ? -dir : -dir + Math.PI / 2,
          });
        }
      }
    }

    // --- the surviving end screen --------------------------------------------
    // The pack's big arched wall loft, standing at the hall's west end where the
    // building held. It is the tallest thing on the plateau and reads from
    // anywhere in the zone.
    const screen = castle.get('Object_22');
    if (screen) {
      const s = 46;
      this.put('citadel-screen', screen.geometry, screen.tris, -HALF_X - 16, 0, rand, {
        scale: s,
        y: baseY,
        yaw: Math.PI / 2,
      });
      this.colliders.push({
        x: -HALF_X - 16,
        z: 0,
        r: 12,
        top: baseY + screen.unitHeight * s,
      });
      this.perch(-HALF_X - 16, baseY + screen.unitHeight * s * 0.9, 0, 14);
    }
    const screen2 = castle.get('Object_60');
    if (screen2) {
      const s = 32;
      this.put('citadel-screen', screen2.geometry, screen2.tris, HALF_X + 14, -22, rand, {
        scale: s,
        y: baseY,
        yaw: Math.PI / 2 + 0.24,
        tilt: 0.1,
        tiltAxis: new Vector3(0, 0, 1),
      });
    }

    // --- the throne ----------------------------------------------------------
    // A cracked dais of concentric steps, and growing straight up out of it the
    // crystal that took the kingdom. It sits at the exact centre of the hall and
    // the breach's light lands on it.
    for (let i = 0; i < 4; i++) {
      const r = 26 - i * 5;
      const g = makeWall(4500 + i, {
        length: r * 2,
        height: 2.6,
        thickness: r * 2,
        ruin: 0.1 + i * 0.06,
        courseHeight: 2.6,
      });
      this.put('citadel-dais', g, this.own(g), 0, 0, rand, {
        yaw: rand() * 0.4,
        y: baseY + 1.5 + i * 2.4,
      });
    }
    this.perch(0, baseY + 11, 0, 30);
    this.colliders.push({ x: 0, z: 0, r: 16, top: baseY + 64 });
  }

  /** A line of fallen drums, as a column comes down and rolls. */
  private scatterDrums(
    x: number,
    z: number,
    radius: number,
    n: number,
    rand: () => number,
    y: number,
  ): void {
    const dir = rand() * Math.PI * 2;
    const key = `drum${Math.floor(radius * 2)}`;
    let geo = DRUM_CACHE.get(key);
    if (!geo) {
      geo = makeDrum(7000 + Math.floor(radius * 10), radius);
      DRUM_CACHE.set(key, geo);
      this.disposables.push(geo);
    }
    const tris = this.triCount(geo);
    for (let i = 0; i < n; i++) {
      // Drums bounce and spread as they fall, so spacing grows down the line.
      const t = (i + 1) / n;
      const d = radius * 2.6 + t * t * radius * 12 + rand() * radius * 2;
      const px = x + Math.cos(dir) * d + (rand() - 0.5) * radius * 3;
      const pz = z + Math.sin(dir) * d + (rand() - 0.5) * radius * 3;
      this.put(key, geo, tris, px, pz, rand, {
        y: y - radius * 0.2,
        tilt: (rand() - 0.5) * 0.5,
        bucket: this.quad(px, pz),
      });
      if (rand() < 0.35) this.perch(px, y + radius, pz, 5);
    }
  }

  // ---- the grand stair ------------------------------------------------------

  /**
   * Three flights climbing the acropolis's west flank, from the head of the
   * avenue to the plateau. The citadel has to be APPROACHED — arriving at it
   * along a rising axis is what makes it feel like the top of a hierarchy rather
   * than just the tallest lump of ground.
   */
  private buildGrandStair(): void {
    const rand = mulberry32(5150);
    const a = KINGDOM.avenue;
    const startX = a.innerX + 4;
    const endX = -KINGDOM.acropolis.plateauR + 6;
    const y0 = this.terrain.heightAt(startX, 0);
    const y1 = this.terrain.heightAt(endX, 0);
    const flights = 3;
    const runTotal = startX - endX;

    let x = startX;
    let y = y0;
    for (let f = 0; f < flights; f++) {
      const steps = 13;
      const rise = (y1 - y0) / (flights * steps);
      const run = runTotal / (flights * steps) - 0.6; // the deficit becomes landings
      const geo = makeStairs(5200 + f, 44 - f * 4, steps, rise, run);
      const tris = this.own(geo);
      // makeStairs climbs along +Z; the avenue climbs along +X (toward x=0).
      this.put('grand-stair', geo, tris, x, 0, rand, {
        yaw: -Math.PI / 2,
        y: y - 1,
      });
      x -= steps * run;
      y += steps * rise;
      // A landing between flights, flanked by a pair of guardian blocks.
      if (f < flights - 1) {
        for (const side of [-1, 1]) {
          const g = makeWall(5300 + f * 2 + (side > 0 ? 1 : 0), {
            length: 9,
            height: 13 - f * 2,
            thickness: 9,
            ruin: 0.25 + f * 0.15,
            courseHeight: 2.2,
          });
          const px = x - 5;
          const pz = side * 26;
          this.put('stair-guardian', g, this.own(g), px, pz, rand, { y: y - 1, yaw: rand() * 0.3 });
          this.perch(px, y + 10, pz, 8);
        }
        x -= 6;
      }
    }
  }

  // ---- the processional avenue ---------------------------------------------

  /**
   * The colonnade flanking the avenue, and what is left of it.
   *
   * Survival falls off toward the gate — the citadel end was maintained longest —
   * so walking in from the gate you pass stumps, then broken shafts, then whole
   * columns, and the architecture itself tells you which way is up-city. Fallen
   * shafts lie ACROSS the road, because that is where a column beside a road
   * ends up, and swimming over them is what makes the avenue feel travelled.
   */
  private buildAvenue(castle: RockPack): void {
    const rand = mulberry32(6120);
    const a = KINGDOM.avenue;
    const OFFSET = a.halfWidth + 9;
    const SPACING = 19;

    const geos = new Map<string, { geo: BufferGeometry; tris: number }>();
    const columnGeo = (ruin: number, h: number, r: number): { geo: BufferGeometry; tris: number } => {
      const key = `${ruin.toFixed(1)}|${Math.round(h)}|${r.toFixed(1)}`;
      let g = geos.get(key);
      if (!g) {
        const geo = makeColumn(6200 + geos.size, { height: h, radius: r, ruin, fluted: true });
        g = { geo, tris: this.own(geo) };
        geos.set(key, g);
      }
      return g;
    };

    for (let x = a.outerX + 26; x <= a.innerX; x += SPACING) {
      // 0 at the gate, 1 at the citadel.
      const t = (x - a.outerX) / (a.innerX - a.outerX);
      for (const side of [-1, 1]) {
        const z = side * OFFSET;
        const ground = this.terrain.heightAt(x, z);
        // Big enough to frame the road. At 24 m these were thin sticks lost
        // against the terraced town behind them, and the avenue stopped reading
        // as a colonnade at all from the gate — which is the one view it exists
        // for.
        const h = 34 + t * 18;
        const r = 2.9 + t * 1.1;
        // Survival rises toward the citadel; a little noise stops it being a
        // perfect gradient, which would read as a graph rather than as decay.
        // The floor is deliberately high: at 0.25 barely anything stood near the
        // gate, and the view straight up the avenue from the gateway — the one
        // shot this whole district exists to compose — had no colonnade in it.
        const survives = rand() < 0.52 + t * 0.4;
        if (survives) {
          const g = columnGeo(0, h, r);
          this.put('avenue-column', g.geo, g.tris, x, z, rand, { y: ground - 1, yaw: rand() * 0.3 });
          this.colliders.push({ x, z, r: r * 1.5, top: ground + h });
          this.perch(x, ground + h, z, 6);
        } else {
          const stump = 0.45 + rand() * 0.4;
          const g = columnGeo(stump, h, r);
          this.put('avenue-column', g.geo, g.tris, x, z, rand, { y: ground - 1, yaw: rand() * 0.5 });
          this.perch(x, ground + h * (1 - stump) * 0.9, z, 7);
          // And the shaft it shed, lying across the road.
          this.scatterDrums(x, z - side * 6, r, 3 + Math.floor(rand() * 3), rand, ground);
        }
      }

      // Kerbs: low blocks marking the road's edge. Cheap, and they do more for
      // the "this is a street" read than anything else on the avenue.
      for (const side of [-1, 1]) {
        const z = side * (a.halfWidth + 1.5);
        if (rand() < 0.22) continue;
        const g = makeWall(6400 + Math.round(x), {
          length: SPACING * 0.92,
          height: 2.2,
          thickness: 3,
          ruin: 0.45 - t * 0.3,
          courseHeight: 2.2,
        });
        this.put('avenue-kerb', g, this.own(g), x, z, rand, {
          yaw: 0,
          y: this.terrain.heightAt(x, z) - 0.6,
          bucket: this.quad(x, z),
        });
      }
    }

    // Two ceremonial arches straddling the avenue, at its thirds.
    for (const f of [0.34, 0.7]) {
      const x = a.outerX + (a.innerX - a.outerX) * f;
      const geo = makeArch(6600 + Math.round(f * 100), {
        span: a.halfWidth * 2 + 14,
        pierHeight: 26,
        thickness: 9,
        width: 7,
        ruin: f < 0.5 ? 0.45 : 0.12,
      });
      const tris = this.own(geo);
      this.put('avenue-arch', geo, tris, x, 0, rand, {
        yaw: Math.PI / 2,
        y: this.terrain.heightAt(x, 0) - 1,
      });
      for (const side of [-1, 1]) {
        this.colliders.push({
          x,
          z: side * (a.halfWidth + 7),
          r: 6,
          top: this.terrain.heightAt(x, 0) + 26,
        });
      }
      this.perch(x, this.terrain.heightAt(x, 0) + 26 + a.halfWidth, 0, 10);
    }

    // A statue base at the head of the avenue, its statue long gone.
    const plinth = castle.get('Object_36') ?? castle.get('Object_8');
    if (plinth) {
      for (const side of [-1, 1]) {
        const x = a.innerX + 12;
        const z = side * 30;
        this.put('avenue-plinth', plinth.geometry, plinth.tris, x, z, rand, {
          scale: 15,
          y: this.terrain.heightAt(x, z) - 1,
        });
        this.perch(x, this.terrain.heightAt(x, z) + 6, z, 9);
      }
    }
  }

  // ---- the great gate -------------------------------------------------------

  /** Twin towers and a half-fallen arch, where the avenue pierces the wall. */
  private buildGate(castle: RockPack): void {
    const rand = mulberry32(7310);
    const gx = KINGDOM.gate.x;
    const halfW = KINGDOM.avenue.halfWidth;

    for (const side of [-1, 1]) {
      const z = side * (halfW + 24);
      const ground = this.terrain.heightAt(gx, z);
      const geo = makeTower(7400 + (side > 0 ? 1 : 0), 34, 58, side > 0 ? 0.22 : 0.44);
      const tris = this.own(geo);
      this.put('gate-tower', geo, tris, gx, z, rand, { y: ground - 2, yaw: 0 });
      this.colliders.push({ x: gx, z, r: 20, top: ground + 58 });
      this.perch(gx, ground + 52, z, 16);
      this.perch(gx + 17, ground + 26, z, 10, new Vector3(1, 0.3, 0).normalize());
    }

    // The gateway itself: a big arch spanning the road, most of one haunch gone.
    const geo = makeArch(7500, {
      span: halfW * 2 + 10,
      pierHeight: 34,
      thickness: 16,
      width: 10,
      ruin: 0.38,
    });
    const tris = this.own(geo);
    this.put('gate-arch', geo, tris, gx, 0, rand, {
      yaw: Math.PI / 2,
      y: this.terrain.heightAt(gx, 0) - 2,
    });

    // The rubble of what fell out of it, spilling down the road.
    const rubbleGeo = makeRubble(7600, 1);
    const rTris = this.own(rubbleGeo);
    for (let i = 0; i < 34; i++) {
      const px = gx + (rand() - 0.5) * 70;
      const pz = (rand() - 0.5) * halfW * 2.4;
      const s = 2 + rand() * rand() * 11;
      this.put('gate-rubble', rubbleGeo, rTris, px, pz, rand, {
        scale: new Vector3(s, s * (0.5 + rand() * 0.6), s),
        sink: s * 0.2,
        tilt: (rand() - 0.5) * 0.7,
      });
    }

    // Blocks from the gate's own facing, big and square.
    const facing = castle.get('Object_24') ?? castle.get('Object_6');
    if (facing) {
      for (let i = 0; i < 12; i++) {
        const px = gx + (rand() - 0.5) * 90;
        const pz = (rand() - 0.5) * 120;
        const s = 7 + rand() * 9;
        this.put('gate-block', facing.geometry, facing.tris, px, pz, rand, {
          scale: s,
          sink: s * 0.22,
          tilt: (rand() - 0.5) * 0.5,
        });
        this.perch(px, this.terrain.heightAt(px, pz) + s * 0.8, pz, 6);
      }
    }
  }

  // ---- the curtain wall -----------------------------------------------------

  /**
   * The ring wall: what makes you feel INSIDE something.
   *
   * Segments are laid round the ring at their local ground height, skipping the
   * gate and skipping the arc the geode swallowed — so the collapse has visibly
   * taken the defences with it, and the breach in the wall is explained by the
   * hole in the ground rather than by decoration.
   */
  private buildCurtainWall(): void {
    const rand = mulberry32(8120);
    const R = KINGDOM.wallR;
    const SEGMENTS = 46;
    const segLen = (2 * Math.PI * R) / SEGMENTS;
    const g = KINGDOM.geode;
    const geodeAngle = Math.atan2(g.z, g.x);
    const geodeArc = Math.atan2(g.r * 0.95, Math.hypot(g.x, g.z));

    // A handful of segment variants, reused around the ring.
    const variants: { geo: BufferGeometry; tris: number }[] = [];
    for (let i = 0; i < 6; i++) {
      const geo = makeWall(8200 + i, {
        length: segLen * 1.04,
        height: 26 + (i % 3) * 7,
        thickness: 7.5,
        ruin: 0.16 + (i / 6) * 0.62,
        crenellated: true,
      });
      variants.push({ geo, tris: this.own(geo) });
    }
    const towerGeos = [0, 1, 2].map((i) => {
      const geo = makeTower(8300 + i, 26, 44 + i * 6, 0.24 + i * 0.16);
      return { geo, tris: this.own(geo) };
    });

    for (let i = 0; i < SEGMENTS; i++) {
      const a = (i / SEGMENTS) * Math.PI * 2;
      // Normalised angular distance from the gate (which sits at a = PI).
      const dGate = Math.abs(Math.atan2(Math.sin(a - Math.PI), Math.cos(a - Math.PI)));
      if (dGate < 0.13) continue; // the gate occupies this arc
      const dGeode = Math.abs(Math.atan2(Math.sin(a - geodeAngle), Math.cos(a - geodeAngle)));
      if (dGeode < geodeArc) continue; // the ground here is gone

      const x = Math.cos(a) * R;
      const z = Math.sin(a) * R;
      const ground = this.terrain.heightAt(x, z);
      // Right at the lip of the collapse the wall is barely there.
      const nearGeode = 1 - Math.min(1, (dGeode - geodeArc) / 0.4);
      const v = variants[Math.min(5, Math.floor(rand() * 4) + Math.floor(nearGeode * 3))];
      const bucket = this.quad(x, z);

      this.put('curtain-wall', v.geo, v.tris, x, z, rand, {
        yaw: tangentYaw(a),
        y: ground - 3,
        bucket,
      });
      this.perch(x, ground + 24, z, 8, new Vector3(Math.cos(a), 0.4, Math.sin(a)).normalize());

      // Towers at regular intervals, as a real curtain has.
      if (i % 6 === 2 && nearGeode < 0.2) {
        const t = towerGeos[i % 3];
        this.put('curtain-tower', t.geo, t.tris, x, z, rand, {
          yaw: tangentYaw(a),
          y: ground - 3,
          bucket,
        });
        this.colliders.push({ x, z, r: 16, top: ground + 44 });
        this.perch(x, ground + 44, z, 12);
      }
    }

    // The rubble fan where the wall slid into the collapse.
    const rubbleGeo = makeRubble(8500, 1);
    const rTris = this.own(rubbleGeo);
    for (let i = 0; i < 60; i++) {
      const a = geodeAngle + (rand() - 0.5) * geodeArc * 2.4;
      const r = R * (0.7 + rand() * 0.42);
      const x = Math.cos(a) * r;
      const z = Math.sin(a) * r;
      const s = 3 + rand() * rand() * 16;
      this.put('wall-rubble', rubbleGeo, rTris, x, z, rand, {
        scale: new Vector3(s, s * (0.45 + rand() * 0.7), s),
        sink: s * 0.22,
        tilt: (rand() - 0.5) * 0.8,
        bucket: this.quad(x, z),
      });
      if (rand() < 0.3) this.perch(x, this.terrain.heightAt(x, z) + s * 0.6, z, 5);
    }
  }

  // ---- the lower town -------------------------------------------------------

  /**
   * The town: ranks of roofless shells on the three terraces.
   *
   * Buildings are laid along each terrace TANGENTIALLY and in blocks separated
   * by radial street gaps, which is how pre-modern hill towns actually grow and
   * — more to the point — is what makes the layout legible from above as you
   * sink in through the breach. Random rotation would destroy this instantly:
   * the alignment IS the town.
   *
   * They are deliberately given NO colliders. They are hollow shells with
   * doorways, the interiors are the interesting part, and a cylinder round each
   * one would lock the player out of the whole district to fix a problem — brief
   * wall clipping at speed — that is far less costly than what it would break.
   */
  private buildLowerTown(): void {
    const rand = mulberry32(9210);
    const variants: { geo: BufferGeometry; tris: number; w: number; d: number; h: number }[] = [];
    for (let i = 0; i < 11; i++) {
      // Tall enough to be BUILDINGS. At 9-22 m with heavy ruin the surviving
      // walls were 4-17 m, and from anywhere above the terraces the district
      // read as a plan of foundations scratched on the ground rather than as a
      // town you could lose a shark in.
      const w = 15 + (i % 4) * 7 + rand() * 4;
      const d = 13 + (i % 3) * 8 + rand() * 4;
      const h = 15 + (i % 5) * 5;
      const geo = makeBuilding(9300 + i, {
        width: w,
        depth: d,
        height: h,
        ruin: 0.2 + (i / 11) * 0.42,
        collapsedCorner: i % 3 === 0,
        rooms: w > 22,
      });
      variants.push({ geo, tris: this.own(geo), w, d, h });
    }

    const g = KINGDOM.geode;
    // Three terrace bands, matching the terrain's three steps.
    const bands = [
      { r: 200, rows: 2, fill: 0.86 },
      { r: 248, rows: 2, fill: 0.8 },
      { r: 292, rows: 1, fill: 0.66 },
    ];

    for (const band of bands) {
      // Block size in radians, and the street gap between blocks.
      const blocks = Math.max(6, Math.round((2 * Math.PI * band.r) / 150));
      const blockArc = (Math.PI * 2) / blocks;
      for (let b = 0; b < blocks; b++) {
        const a0 = b * blockArc + 0.06;
        const a1 = (b + 1) * blockArc - 0.06; // the gap between them is a street
        const along = (a1 - a0) * band.r;
        const perBlock = Math.max(1, Math.floor((along / 26) * band.fill));
        for (let k = 0; k < perBlock; k++) {
          for (let row = 0; row < band.rows; row++) {
            if (rand() > band.fill) continue;
            const a = a0 + ((k + 0.5) / perBlock) * (a1 - a0);
            const r = band.r + (row - (band.rows - 1) / 2) * 26 + (rand() - 0.5) * 5;
            const x = Math.cos(a) * r;
            const z = Math.sin(a) * r;
            // Never in the road, never in the hole.
            if (avenueMask(x, z) > 0.05) continue;
            if (Math.hypot(x - g.x, z - g.z) < g.r * 0.98) continue;
            if (this.terrain.slopeAt(x, z) > 2.6) continue;

            const v = variants[Math.floor(rand() * variants.length)];
            const ground = this.terrain.heightAt(x, z);
            this.put('town-house', v.geo, v.tris, x, z, rand, {
              // Aligned to the street, with only a degree or two of slop.
              yaw: tangentYaw(a) + (rand() - 0.5) * 0.12,
              y: ground - 1.5,
              bucket: this.quad(x, z),
            });
            // Wall tops are where crystal and weed take hold.
            this.perch(x, ground + v.h * 0.85, z, 5 + rand() * 4);
            if (rand() < 0.4) {
              this.perch(
                x + (rand() - 0.5) * v.w,
                ground + v.h * 0.5,
                z + (rand() - 0.5) * v.d,
                4,
              );
            }
          }
        }
      }
    }

    // Loose rubble and slabs through the streets, so the ground between the
    // shells is not swept clean.
    const rubbleGeo = makeRubble(9500, 1);
    const rTris = this.own(rubbleGeo);
    const slabGeo = makeSlab(9510);
    const sTris = this.own(slabGeo);
    for (let i = 0; i < 220; i++) {
      const a = rand() * Math.PI * 2;
      const r = KINGDOM.acropolis.r + rand() * (KINGDOM.wallR - KINGDOM.acropolis.r);
      const x = Math.cos(a) * r;
      const z = Math.sin(a) * r;
      if (Math.hypot(x - g.x, z - g.z) < g.r) continue;
      if (avenueMask(x, z) > 0.4) continue;
      const s = 1.6 + rand() * rand() * 12;
      const slab = rand() < 0.3;
      this.put(slab ? 'town-slab' : 'town-rubble', slab ? slabGeo : rubbleGeo, slab ? sTris : rTris, x, z, rand, {
        scale: new Vector3(s, s * (slab ? 0.5 + rand() * 0.9 : 0.45 + rand() * 0.7), s),
        sink: s * 0.2,
        tilt: (rand() - 0.5) * (slab ? 0.5 : 0.8),
        bucket: this.quad(x, z),
      });
      if (rand() < 0.22) this.perch(x, this.terrain.heightAt(x, z) + s * 0.5, z, 4);
    }
  }

  // ---- the sunken cathedral -------------------------------------------------

  /**
   * The geode: the collapse basin, and the reason the kingdom fell.
   *
   * The composition here is deliberately the inverse of the rest of the zone —
   * up top, architecture with crystal growing through it; down here, crystal
   * with architecture drowning in it. Buildings on the slope are tilted INTO the
   * basin, which is the one place in the city where things are not level, and
   * that break in the rules is what makes the place read as a catastrophe.
   */
  private buildGeode(castle: RockPack, bigCrystal: RockPack): void {
    const rand = mulberry32(10310);
    const g = KINGDOM.geode;
    const e = KINGDOM.exit;

    // Buildings sliding down the crater wall.
    const variants: { geo: BufferGeometry; tris: number; h: number }[] = [];
    for (let i = 0; i < 4; i++) {
      const geo = makeBuilding(10400 + i, {
        width: 16 + i * 5,
        depth: 13 + i * 4,
        height: 11 + i * 3,
        ruin: 0.45 + i * 0.12,
        collapsedCorner: true,
      });
      variants.push({ geo, tris: this.own(geo), h: 11 + i * 3 });
    }
    for (let i = 0; i < 22; i++) {
      const a = rand() * Math.PI * 2;
      const r = g.r * (0.5 + rand() * 0.45);
      const x = g.x + Math.cos(a) * r;
      const z = g.z + Math.sin(a) * r;
      if (Math.hypot(x - e.x, z - e.z) < e.radius * 2.2) continue;
      const v = variants[Math.floor(rand() * variants.length)];
      const ground = this.terrain.heightAt(x, z);
      // Tipped toward the middle of the hole, by however steep the slope is.
      const toward = Math.atan2(g.z - z, g.x - x);
      this.put('geode-ruin', v.geo, v.tris, x, z, rand, {
        yaw: -toward + Math.PI / 2,
        y: ground - 2,
        tilt: 0.18 + rand() * 0.4,
        tiltAxis: new Vector3(1, 0, 0),
      });
      this.perch(x, ground + v.h * 0.7, z, 7);
    }

    // A tower that went in whole and is now lying on its side at the bottom.
    {
      const geo = makeTower(10500, 24, 52, 0.3);
      const tris = this.own(geo);
      const x = g.x - 54;
      const z = g.z + 40;
      this.put('geode-tower', geo, tris, x, z, rand, {
        y: this.terrain.heightAt(x, z) + 22,
        yaw: 1.1,
        tilt: 1.42, // very nearly flat on its face
        tiltAxis: new Vector3(1, 0, 0),
      });
      this.perch(x, this.terrain.heightAt(x, z) + 14, z, 14);
    }

    // The cathedral itself: the pack's great arches, half-drowned in the shards.
    const arch = castle.get('Object_22');
    if (arch) {
      for (let i = 0; i < 3; i++) {
        const a = -0.6 + i * 0.85;
        const r = g.r * 0.42;
        const x = g.x + Math.cos(a) * r;
        const z = g.z + Math.sin(a) * r;
        const s = 34 + rand() * 16;
        this.put('geode-arch', arch.geometry, arch.tris, x, z, rand, {
          scale: s,
          y: this.terrain.heightAt(x, z) - 6,
          yaw: -a,
          tilt: (rand() - 0.5) * 0.3,
          tiltAxis: new Vector3(0, 0, 1),
        });
        this.colliders.push({ x, z, r: 10, top: this.terrain.heightAt(x, z) + arch.unitHeight * s });
        this.perch(x, this.terrain.heightAt(x, z) + arch.unitHeight * s * 0.5, z, 16);
      }
    }

    // The colossal crystals. This model is 88 m tall for 790 triangles, which
    // makes it the cheapest landmark in the game — so the basin gets a forest of
    // them at full size, and they are what you see first coming over the rim.
    const big = bigCrystal.pieces[0];
    if (big) {
      big.material = this.crystalMat;
      const COUNT = 16;
      for (let i = 0; i < COUNT; i++) {
        const a = (i / COUNT) * Math.PI * 2 + rand() * 0.5;
        const r = g.r * (0.2 + rand() * 0.72);
        const x = g.x + Math.cos(a) * r;
        const z = g.z + Math.sin(a) * r;
        if (Math.hypot(x - e.x, z - e.z) < e.radius * 1.8) continue;
        const s = 0.5 + rand() * rand() * 1.05;
        const height = big.unitHeight * s * 88;
        this.put('geode-crystal', big.geometry, big.tris, x, z, rand, {
          scale: s * 88,
          y: this.terrain.heightAt(x, z) - height * 0.18,
          tilt: (rand() - 0.5) * 0.45,
          mat: this.crystalMat,
          color: crystalTint(rand, 0.95),
        });
        this.colliders.push({
          x,
          z,
          r: height * 0.2,
          top: this.terrain.heightAt(x, z) + height * 0.7,
        });
        this.perch(x, this.terrain.heightAt(x, z) + height * 0.2, z, 12);
      }
    }
  }

  // ---- outside the walls ----------------------------------------------------

  /**
   * The land outside the curtain: bedrock, boulder fields, and a thin scatter of
   * outbuildings. Its whole job is to make the wall read as a boundary — a
   * fortification with nothing on the far side of it is just a fence.
   */
  private buildOutskirts(): void {
    const rand = mulberry32(11310);
    const rubbleGeo = makeRubble(11400, 1);
    const rTris = this.own(rubbleGeo);
    const slabGeo = makeSlab(11410);
    const sTris = this.own(slabGeo);

    for (let i = 0; i < 260; i++) {
      const a = rand() * Math.PI * 2;
      const r = KINGDOM.wallR + 12 + rand() * 46;
      const x = Math.cos(a) * r;
      const z = Math.sin(a) * r;
      if (Math.abs(x) > KINGDOM.maxX - 30 || Math.abs(z) > KINGDOM.maxZ - 30) continue;
      const slab = rand() < 0.42;
      const s = 3 + rand() * rand() * 26;
      this.put(slab ? 'outer-slab' : 'outer-rubble', slab ? slabGeo : rubbleGeo, slab ? sTris : rTris, x, z, rand, {
        scale: new Vector3(s, s * (slab ? 0.6 + rand() * 1.4 : 0.5 + rand() * 0.8), s),
        sink: s * 0.18,
        tilt: (rand() - 0.5) * 0.6,
        bucket: this.quad(x, z),
      });
      if (s > 14) {
        this.colliders.push({ x, z, r: s * 0.4, top: this.terrain.heightAt(x, z) + s * 0.7 });
      }
      if (rand() < 0.3) this.perch(x, this.terrain.heightAt(x, z) + s * 0.55, z, 5);
    }

    // A few outbuildings, farmsteads that never made it inside the wall.
    const geo = makeBuilding(11500, {
      width: 15,
      depth: 12,
      height: 9,
      ruin: 0.6,
      collapsedCorner: true,
    });
    const tris = this.own(geo);
    for (let i = 0; i < 14; i++) {
      const a = rand() * Math.PI * 2;
      const r = KINGDOM.wallR + 18 + rand() * 32;
      const x = Math.cos(a) * r;
      const z = Math.sin(a) * r;
      if (Math.abs(x) > KINGDOM.maxX - 40 || Math.abs(z) > KINGDOM.maxZ - 40) continue;
      if (this.terrain.slopeAt(x, z) > 2.4) continue;
      const ground = this.terrain.heightAt(x, z);
      this.put('outer-house', geo, tris, x, z, rand, {
        yaw: rand() * Math.PI * 2,
        y: ground - 1.5,
        bucket: this.quad(x, z),
      });
      this.perch(x, ground + 8, z, 5);
    }
  }

  // ---- the crystal ----------------------------------------------------------

  /**
   * Crystal, placed in FLOWERING BURSTS rather than scattered.
   *
   * A burst is a set of shards fanned out of one origin, splaying wider and
   * shortening as they go — which is how mineral actually grows out of a crack,
   * and it is the difference between a geode and a handful of gravel. Every
   * burst is anchored to a perch the city recorded while it was being built: a
   * wall top, a broken column, a rubble face, a crater slope. So the crystal is
   * growing out of the kingdom rather than sitting next to it.
   */
  private buildCrystal(gemsLow: RockPack, gemsMed: RockPack, bigCrystal: RockPack): void {
    const rand = mulberry32(12310);
    const g = KINGDOM.geode;

    for (const p of gemsLow.pieces) p.material = this.crystalMat;
    for (const p of gemsMed.pieces) p.material = this.crystalMat;
    const shards = gemsLow.pieces;
    const spears = gemsMed.pieces;
    if (shards.length === 0) return;

    // --- bursts on the city's own ruins --------------------------------------
    for (const perch of this.perches) {
      if (rand() > 0.72) continue;
      const inGeode = Math.hypot(perch.x - g.x, perch.z - g.z) < g.r;
      const n = Math.round((3 + rand() * 7) * (inGeode ? 1.9 : 1));
      this.burst(shards, spears, perch, n, perch.size * (inGeode ? 1.5 : 1), rand, inGeode);
    }

    // --- bursts straight out of the ground -----------------------------------
    // Density is driven by distance from the geode: the mineral is welling up
    // from there, so the city is progressively more infested as you move east.
    for (let i = 0; i < 900; i++) {
      const x = KINGDOM.minX + 40 + rand() * (KINGDOM.maxX - KINGDOM.minX - 80);
      const z = KINGDOM.minZ + 40 + rand() * (KINGDOM.maxZ - KINGDOM.minZ - 80);
      const gd = Math.hypot(x - g.x, z - g.z);
      const infest = 1 - Math.min(1, gd / (g.r * 3.4));
      if (rand() > 0.1 + infest * 0.85) continue;
      if (this.terrain.slopeAt(x, z) > 3.2) continue;
      const inGeode = gd < g.r;
      const y = this.terrain.heightAt(x, z);
      const size = (3 + rand() * rand() * 12) * (inGeode ? 2.1 : 1);
      this.burst(
        shards,
        spears,
        { x, y, z, n: UP, size },
        3 + Math.floor(rand() * (inGeode ? 12 : 7)),
        size,
        rand,
        inGeode,
      );
    }

    // --- the throne, and the landmark crystals out in the city ---------------
    const big = bigCrystal.pieces[0];
    if (big) {
      big.material = this.crystalMat;
      const baseY = this.terrain.heightAt(0, 0);
      // The throne: the largest single object in the zone, dead centre, lit by
      // the breach. Everything about this zone points at it.
      // Fixed colour, not a roll of the dice. Every other crystal in the zone
      // takes its hue at random, but the throne is the one object the whole
      // composition points at — it gets a deliberate royal violet, which is the
      // only warm-shifted thing standing in a shaft of cold blue light, and so
      // it separates from the beam instead of dissolving into it.
      this.put('throne-crystal', big.geometry, big.tris, 0, 0, rand, {
        scale: 82,
        y: baseY + 4,
        yaw: 0.6,
        mat: this.crystalMat,
        color: new Color(0.44, 0.13, 1.0),
      });

      // And a handful of giants standing in the town, so the citadel's crystal
      // is clearly the same thing that is coming up everywhere else.
      const spots: [number, number][] = [
        [-215, -150],
        [120, -240],
        [-260, 190],
        [255, -130],
        [-120, 265],
        [60, 300],
        [-320, -70],
        [300, 250],
      ];
      for (const [x, z] of spots) {
        const s = 26 + rand() * 34;
        const y = this.terrain.heightAt(x, z);
        this.put('city-crystal', big.geometry, big.tris, x, z, rand, {
          scale: s,
          y: y - big.unitHeight * s * 0.16,
          tilt: (rand() - 0.5) * 0.35,
          mat: this.crystalMat,
          color: crystalTint(rand, 0.9),
          bucket: this.quad(x, z),
        });
        this.colliders.push({ x, z, r: s * 0.22, top: y + big.unitHeight * s * 0.7 });
      }
    }
  }

  /**
   * One flowering burst. Shards fan around `perch.n`, each leaning further out
   * and growing shorter the further it is from the axis — a real crystal cluster
   * has its longest blade up the middle.
   */
  private burst(
    shards: RockPiece[],
    spears: RockPiece[],
    perch: Perch,
    count: number,
    size: number,
    rand: () => number,
    rich: boolean,
  ): void {
    const axis = perch.n;
    // A stable pair of vectors perpendicular to the axis, to swing shards around.
    const side = new Vector3(0, 1, 0);
    if (Math.abs(axis.y) > 0.9) side.set(1, 0, 0);
    const u = new Vector3().crossVectors(axis, side).normalize();
    const v = new Vector3().crossVectors(axis, u).normalize();

    const dir = new Vector3();
    const pos = new Vector3();
    const q = new Quaternion();
    const m = new Matrix4();
    const scl = new Vector3();
    const bucket = this.quad(perch.x, perch.z);

    for (let i = 0; i < count; i++) {
      const t = i / Math.max(1, count - 1);
      // The first blade goes straight up the axis; the rest splay progressively.
      const spread = i === 0 ? 0.05 : 0.12 + Math.pow(rand(), 0.55) * 1.15;
      const az = rand() * Math.PI * 2;
      dir
        .copy(axis)
        .multiplyScalar(Math.cos(spread))
        .addScaledVector(u, Math.sin(spread) * Math.cos(az))
        .addScaledVector(v, Math.sin(spread) * Math.sin(az))
        .normalize();

      // Long up the middle, short at the fringe.
      const len = size * (1 - t * 0.5) * (0.45 + rand() * 0.8) * (1 - spread * 0.28);
      if (len < 0.5) continue;

      // Prefer the fat medium-poly spears for the few biggest blades in a rich
      // burst; the 52-triangle shards do everything else, which is what makes
      // thousands of these affordable.
      const useSpear = rich && spears.length > 0 && i < 2 && len > size * 0.5;
      const piece = useSpear
        ? spears[Math.floor(rand() * spears.length)]
        : shards[Math.floor(rand() * shards.length)];

      const s = len / Math.max(piece.unitHeight, 1e-3);
      // Shards emerge from a common point just under the surface.
      pos
        .set(perch.x, perch.y, perch.z)
        .addScaledVector(dir, len * 0.08)
        .addScaledVector(axis, -size * 0.12);
      q.setFromUnitVectors(UP, dir);
      // Spears are modelled lying along X, so stand them up first.
      if (useSpear) q.multiply(SPEAR_UPRIGHT);
      scl.set(s * (0.8 + rand() * 0.5), s, s * (0.8 + rand() * 0.5));
      m.compose(pos, q, scl);
      this.add(
        useSpear ? 'crystal-spear' : `crystal-shard${shards.indexOf(piece)}`,
        piece.geometry,
        this.crystalMat,
        piece.tris,
        m,
        crystalTint(rand, rich ? 0.95 : 0.78),
        bucket,
      );
    }
  }

  // ---- vegetation -----------------------------------------------------------

  /**
   * Weed, in the cracks. Cheap species carry the volume, a handful of expensive
   * corals appear as accents, and the luminescent plant — 26 k triangles apiece —
   * is placed a dozen times at enormous scale as the drowned city's own lamps.
   *
   * Materials are alpha-TESTED, never blended: these models ship transparent and
   * double-sided, which at thousands of instances kills early-z, forces
   * back-to-front sorting, and doubles the fragment count. The Drowned Garden
   * measured that at 30-40 fps; alpha test renders them essentially free.
   */
  private async buildVegetation(loader: AssetLoaderLike): Promise<void> {
    const specs: {
      url: string;
      seed: number;
      onPerch: number;
      ground: number;
      small: [number, number];
      big: [number, number];
      bigChance: number;
      glow?: boolean;
    }[] = [
      // Sizes are metres along the model's LONGEST axis (see the normalisation
      // note in the loader) and are deliberately modest. This is weed in the
      // cracks of a city; the moment it out-scales the masonry the zone stops
      // being a kingdom and turns into a reef with some rubble in it.
      //
      // The cheap bulk.
      { url: algae1Url, seed: 2001, onPerch: 180, ground: 240, small: [1.5, 5], big: [7, 13], bigChance: 0.06 },
      { url: algae2Url, seed: 2002, onPerch: 180, ground: 240, small: [1.5, 5], big: [7, 13], bigChance: 0.06 },
      { url: seaweedUrl, seed: 2003, onPerch: 150, ground: 210, small: [2.5, 8], big: [12, 20], bigChance: 0.07 },
      { url: seaweed2Url, seed: 2004, onPerch: 120, ground: 180, small: [2.5, 8], big: [12, 20], bigChance: 0.07 },
      { url: lowPolyPlantUrl, seed: 2005, onPerch: 80, ground: 130, small: [2, 5], big: [7, 12], bigChance: 0.05 },
      { url: lowPolyShrubUrl, seed: 2006, onPerch: 110, ground: 160, small: [1.5, 4.5], big: [6, 11], bigChance: 0.07 },
      { url: coral2Url, seed: 2007, onPerch: 70, ground: 100, small: [2.5, 7], big: [10, 17], bigChance: 0.1 },
      // Mid cost.
      { url: marinePlantUrl, seed: 2008, onPerch: 22, ground: 34, small: [3, 8], big: [11, 18], bigChance: 0.15 },
      // Expensive accents: single figures, deliberately.
      { url: lowpolyCoralUrl, seed: 2009, onPerch: 7, ground: 11, small: [5, 11], big: [15, 24], bigChance: 0.3 },
      { url: coralPieceUrl, seed: 2010, onPerch: 6, ground: 9, small: [5, 10], big: [14, 22], bigChance: 0.3 },
      // The lamps: eight in the whole city, genuinely huge, and the only weed
      // allowed to compete with the architecture.
      { url: luminescentUrl, seed: 2011, onPerch: 4, ground: 4, small: [22, 32], big: [40, 56], bigChance: 0.45, glow: true },
    ];

    await Promise.all(
      specs.map(async (spec) => {
        try {
          const gltf = await loader.loadGLB(spec.url);
          gltf.scene.updateMatrixWorld(true);
          let src: Mesh | null = null;
          gltf.scene.traverse((o) => {
            const mesh = o as Mesh;
            if (!src && mesh.isMesh && mesh.geometry) src = mesh;
          });
          if (!src) return;
          const mesh = src as Mesh;
          const geo = mesh.geometry.clone();
          geo.applyMatrix4(mesh.matrixWorld);
          const box = new Box3().setFromBufferAttribute(geo.attributes.position as never);
          const size = box.getSize(new Vector3());
          const center = box.getCenter(new Vector3());
          // Normalise by the LONGEST axis, not by height.
          //
          // This is the single worst bug the first pass of this zone shipped.
          // Normalising by height means a size of 40 gives a 40 m TALL plant —
          // but luminescent_plants is modelled 2.0 wide by 1.0 tall, so 40
          // produced an 80 m wide sheet of glowing leaf, and low-poly_plant
          // (48 x 31) produced a 62 m one. The city vanished under salad. Keying
          // on the longest axis makes every size number mean the same thing
          // across every species: metres across, whatever shape the model is.
          const s = 1 / Math.max(size.x, size.y, size.z, 1e-4);
          geo.translate(-center.x, -box.min.y, -center.z);
          geo.scale(s, s, s);
          this.disposables.push(geo);

          const raw = (Array.isArray(mesh.material) ? mesh.material[0] : mesh.material) as MeshStandardMaterial;
          const mat = raw.clone();
          mat.transparent = false;
          mat.alphaTest = 0.45;
          mat.depthWrite = true;
          mat.side = DoubleSide; // fronds are flat cards; one side would vanish
          mat.roughness = 0.95;
          mat.metalness = 0;
          if (spec.glow) {
            // Cool teal rather than the model's own acid green, so the lamps
            // read as part of the crystal's colour story instead of fighting it.
            mat.emissive = new Color(0x1f9ec4);
            mat.emissiveMap = mat.map;
            mat.emissiveIntensity = 1.5;
          }
          this.disposables.push(mat);

          this.plant(spec, geo, mat, this.triCount(geo));
        } catch (err) {
          console.warn('[404hz] kingdom vegetation failed to load', spec.url, err);
        }
      }),
    );
    this.flush();
  }

  private plant(
    spec: {
      seed: number;
      onPerch: number;
      ground: number;
      small: [number, number];
      big: [number, number];
      bigChance: number;
    },
    geo: BufferGeometry,
    mat: MeshStandardMaterial,
    triPer: number,
  ): void {
    const rand = mulberry32(spec.seed);
    const m = new Matrix4();
    const q = new Quaternion();
    const scl = new Vector3();
    const p = new Vector3();
    const c = new Color();

    const put = (x: number, y: number, z: number, forceBig = false): void => {
      if (Math.abs(x) > KINGDOM.maxX - 30 || Math.abs(z) > KINGDOM.maxZ - 30) return;
      const big = forceBig || rand() < spec.bigChance;
      const range = big ? spec.big : spec.small;
      const h = range[0] + rand() * (range[1] - range[0]);
      scl.set(h, h, h);
      q.setFromAxisAngle(UP, rand() * Math.PI * 2);
      p.set(x, y - h * 0.04, z);
      m.compose(p, q, scl);
      // Muted, cold, and varied. The stock models are a saturated spring green
      // that reads as a garden centre; this pulls them toward the drowned
      // blue-green the rest of the zone is lit in.
      const v = 0.3 + rand() * 0.6;
      c.setRGB(v * 0.5, v * 0.8, v * 0.72);
      this.add(`plant${spec.seed}`, geo, mat, triPer, m, c, this.quad(x, z));
    };

    // Growing out of the ruins: the perches the city recorded.
    for (let i = 0; i < spec.onPerch && this.perches.length > 0; i++) {
      const perch = this.perches[Math.floor(rand() * this.perches.length)];
      put(
        perch.x + (rand() - 0.5) * perch.size,
        perch.y,
        perch.z + (rand() - 0.5) * perch.size,
        rand() < 0.1,
      );
    }

    // And on the ground, in loose clumps rather than an even rash.
    let placed = 0;
    for (let tries = 0; tries < spec.ground * 14 && placed < spec.ground; tries++) {
      const cx = KINGDOM.minX + 50 + rand() * (KINGDOM.maxX - KINGDOM.minX - 100);
      const cz = KINGDOM.minZ + 50 + rand() * (KINGDOM.maxZ - KINGDOM.minZ - 100);
      if (this.terrain.slopeAt(cx, cz) > 2.2) continue;
      if (avenueMask(cx, cz) > 0.6) continue; // the road stayed swept
      const clump = 1 + Math.floor(rand() * 5);
      for (let k = 0; k < clump && placed < spec.ground; k++) {
        const x = cx + (rand() - 0.5) * 24;
        const z = cz + (rand() - 0.5) * 24;
        put(x, this.terrain.heightAt(x, z), z);
        placed++;
      }
    }
  }

  // ---- lifecycle ------------------------------------------------------------

  /**
   * The geode's contents are only ever seen from the basin or its rim, and they
   * are the densest thing in the zone, so drop them wholesale once you are well
   * away. The fog reaches that far anyway, so nothing is ever seen to vanish.
   */
  update(camera: PerspectiveCamera): void {
    const g = KINGDOM.geode;
    const d = Math.hypot(camera.position.x - g.x, camera.position.z - g.z);
    this.geodeGroup.visible = d < g.r * 3.6;
  }

  dispose(): void {
    for (const p of this.packs) p.dispose();
    this.packs.length = 0;
    for (const d of this.disposables) d.dispose();
    this.disposables.length = 0;
    this.colliders.length = 0;
    this.perches.length = 0;
    DRUM_CACHE.clear();
  }
}

// ---- module-scope scratch --------------------------------------------------

const SCRATCH_COLOR = new Color();
const STONE_STAIN = new Color(0.4, 0.52, 0.62);
/** Fallen drums are shared between every column of the same radius. */
const DRUM_CACHE = new Map<string, BufferGeometry>();
/** The medium-poly gems are modelled lying along X; this stands one upright. */
const SPEAR_UPRIGHT = new Quaternion().setFromAxisAngle(new Vector3(0, 0, 1), Math.PI / 2);

/**
 * A crystal's glow colour. Weighted toward the cold blues that read as "deep",
 * with occasional violet and a rare warm gold — the rare one matters more than
 * the common ones, because a field of uniformly blue crystal reads as a colour
 * filter rather than as mineral.
 */
function crystalTint(rand: () => number, gain: number): Color {
  const r = rand();
  const c = new Color();
  // High chroma, moderate luminance. Glow has to come from SATURATION here, not
  // from brightness — see the note on tone mapping in makeCrystalMaterial.
  if (r < 0.54) c.setRGB(0.1, 0.46, 1.0); // cold blue
  else if (r < 0.79) c.setRGB(0.12, 0.88, 0.86); // cyan
  else if (r < 0.93) c.setRGB(0.52, 0.2, 1.0); // violet
  else c.setRGB(1.0, 0.54, 0.1); // rare gold
  return c.multiplyScalar(gain * (0.72 + rand() * 0.42));
}
